name: Hourly Reminder Check

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:


jobs:
  check-deadlines:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Route
        run: |
          curl -i -X GET "https://mof-project-tracker.vercel.app/api/cron" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"

